export const ANALYTICS_CONSTANTS = {
  MAX_WORD_FREQUENCY: 20,
  MAX_NOVEL_RANKING: 10,
  MIN_WORD_LENGTH: 2,
  MAX_WORD_LENGTH: 10,
  MAX_BUBBLE_RADIUS: 150,
  MIN_BUBBLE_RADIUS: 40,
  BUBBLE_MARGIN: 25,
  MAX_BUBBLE_ATTEMPTS: 50,
} as const; 